# Runs the test suite when a push to a /feature branch occurs.
name: Continuous Integration

on:
  push:
    branches: ["*/*"]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm test
      - run: npm run build
